package com.sheandsoul.v1update.entities;

public enum SymptomLocation {

    SUBAREOLAR,
    NIPPLE_CENTRAL,
    UPPER_OUTER_QUADRANT,
    UPPER_INNER_QUADRANT,
    LOWER_OUTER_QUADRANT,
    LOWER_INNER_QUADRANT,
    AXILLARY_UNDERARM,
    SUPRACLAVICULAR,
    INFRACLAVICULAR,
    SKIN_DIMPLING,
    NIPPLE_DISCHARGE,
    PERSISTENT_PAIN

}
